// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <main className="flex w-full h-screen bg-gray-100">
          <div className="bg-blue-400 h-full sm:w-32"></div>
          <div className=" h-full w-full overflow-y-hidden">
            <Navbar />
            <div className="overflow-y-auto h-full w-full p-4 pt-0 pb-14 ">
            {children}
            </div>
            </div>
        </main>
      </body>
    </html>
  );
}
